/** Plain-language definitions for assumption fields (shown via ? help). */
export const FIELD_DEFINITIONS: Record<string, string> = {
  'newHire.hiringPlanPerPeriod':
    'Target new hires started each planning period (week or month, depending on simulator granularity).',
  'newHire.classSize': 'Average trainees per hiring class entering the training pipeline.',
  'newHire.trainingWeeks': 'Weeks agents spend in classroom training before nesting.',
  'newHire.trainingAttritionRate': 'Share of each hiring class expected to attrite during the full training stage.',
  'newHire.graduationRate': 'Share of trainees who complete training and graduate to production (0–1).',
  'newHire.nestingWeeks': 'Supervised nesting period after graduation before full production.',
  'newHire.nestingAttritionRate': 'Share of each class expected to attrite during the full nesting stage.',
  'newHire.nestingPhoneTimePct': 'Default productive phone-time share applied to nesting headcount when no week-by-week ramp is defined.',
  'newHire.graduationWeek': 'Week number from training start when surviving nesters graduate into production headcount.',
  'newHire.timeToProficiencyWeeks': 'Weeks until a new hire reaches full productivity target.',
  'newHire.hiringDelayWeeks': 'Lag between approval and agents appearing on schedule.',
  'newHire.trainingCostPerHire': 'One-time training cost per hire (materials, trainer time, systems).',
  'tenured.beginningProductionHeadcount': 'Starting production headcount in week 1 before graduates and attrition are applied.',
  'tenured.attritionRateMonthly': 'Monthly voluntary + involuntary attrition as a fraction of scheduled headcount.',
  'tenured.shrinkageRate': 'Total shrinkage (paid time not available for production) as a fraction of scheduled hours.',
  'tenured.shrinkageInOfficeShare': 'Portion of shrinkage hours attributed to in-office activities (meetings, coaching, etc.).',
  'tenured.standardScheduledHoursPerWeek': 'Contracted scheduled hours per FTE per week before shrinkage.',
  'tenured.otHoursPerFtePerWeek': 'Average overtime hours per FTE per week.',
  'tenured.vtoHoursPerFtePerWeek': 'Average voluntary time-off hours per FTE per week.',
  'tenured.occupancyTarget': 'Share of available time spent on handled contacts (0–1).',
  'tenured.productivityFactor': 'Efficiency multiplier vs. standard (AHT, quality); 1.0 = target.',
  'tenured.attendanceRate': 'Share of scheduled shifts with attendance (0–1).',
  'tenured.scheduleAdherence': 'Share of time agents follow their schedule (0–1).',
  'tenured.ahtSeconds': 'Average handle time per contact in seconds.',
  'tenured.utilizationTarget': 'Share of logged-in time on productive work (0–1).',
  'tenured.crossSkilledShare': 'Fraction of workforce cross-trained across queues.',
  'tenured.productiveHoursPerFtePerWeek': 'Core production hours per FTE per week after shrinkage, before nesting phone-time adders.',
  'tenured.laborCostPerFteMonthly': 'Fully loaded monthly labor cost per scheduled FTE.',
  'business.baseForecastVolume': 'Monthly contact volume at period zero before growth and seasonality.',
  'business.growthRateMonthly': 'Month-over-month volume growth rate (e.g. 0.02 = 2%).',
  'business.serviceLevelTarget': 'Target service level (% of contacts answered within SLA).',
  'business.asaTargetSeconds': 'Average speed of answer SLA target in seconds.',
  'business.responseTimeTargetSeconds': 'Non-voice response time SLA target in seconds.',
  'business.budgetConstraintMonthly': 'Monthly operating budget ceiling for labor and related costs.',
  'business.revenueTargetMonthly': 'Monthly revenue target from handled volume.',
  'business.requiredOccupancy': 'Minimum occupancy required to meet client SLA.',
  'business.staffingBufferPct': 'Extra FTE buffer above calculated requirement (e.g. 0.05 = 5%).',
  'business.revenuePerContact': 'Average revenue earned per handled contact.',
  'business.billingRate': 'Billing rate for financial projections: USD per hour (Production Hours & FTE) or USD per transaction.',
  'business.hourlySalaryUsd': 'Standard production labor rate in USD per hour for capacity-aligned cost.',
  'business.supportSalaryUsd': 'Weekly support salary overhead in USD.',
  'business.trainingSalaryRateUsd': 'Training pipeline salary rate in USD per HC per week (Training + Nesting HC).',
  'business.otherCostUsd': 'Weekly other operating cost in USD.',
  'business.slaPenaltyPerMissedPoint': 'Financial penalty per service-level point missed.',
  'business.overtimeMultiplier': 'Pay multiplier for overtime hours (e.g. 1.5 = time-and-a-half).',
  'channels.forecastVolume': 'Forecast volume for this channel in the planning period.',
  'channels.ahtSeconds': 'Average handle time or processing time in seconds for this channel.',
  'channels.paidHoursPerFte': 'Paid scheduled hours per FTE per week for this channel.',
  'channels.occupancyTarget': 'Share of available time spent handling contacts (voice/chat).',
  'channels.shrinkagePct': 'Shrinkage applied once per channel: Required HC = Required FTE ÷ (1 − Shrinkage).',
  'channels.productivityPct': 'Productivity factor for async channels (email, back office, etc.).',
  'channels.chatConcurrency': 'Number of simultaneous chats per agent (chat channel only).',
  'channels.channelMixPct': 'Share of total LOB volume attributed to this channel.',
  'channels.revenuePerContact': 'Revenue earned per handled contact/transaction for this channel.',
  'channels.startingProductionHc': 'Week 0 production headcount for this channel. Default is 0 for new plans.',
  'channels.trainingWeeks': 'Classroom training duration in weeks for this channel.',
  'channels.nestingWeeks': 'Supervised nesting period in weeks for this channel.',
  'channels.classSize': 'Average trainees per hiring class for this channel.',
  'channels.trainingAttritionRate': 'Share of each class expected to attrite during training for this channel.',
  'channels.nestingAttritionRate': 'Share of each class expected to attrite during nesting for this channel.',
  'channels.graduationRate': 'Share of trainees who graduate to production for this channel.',
  'channels.nestingPhoneTimePct': 'Productive handle-time share for nesting agents on this channel.',
}
