import { fmtCurrency, fmtNum, fmtPct } from './format'
import { METRIC_LABELS } from './metricLabels'
import type { ActualsSnapshot, PeriodResult } from './types'

export type VarianceMetricDef = {
  key: string
  label: string
  category: string
  planKey: keyof PeriodResult
  actualKey: keyof PeriodResult | null
  actualsKey: keyof ActualsSnapshot | null
  higherIsBetter: boolean
  fmt: (v: number) => string
  pct?: boolean
}

export const VARIANCE_METRIC_CATEGORIES = [
  'Workforce',
  'Hours',
  'Shrinkage',
  'Performance',
  'Financial',
] as const

export const VARIANCE_METRICS: VarianceMetricDef[] = [
  {
    key: 'requiredFte',
    label: METRIC_LABELS.requiredHeadcount,
    category: 'Workforce',
    planKey: 'requiredFte',
    actualKey: null,
    actualsKey: null,
    higherIsBetter: true,
    fmt: (v) => fmtNum(v, 1),
  },
  {
    key: 'scheduledFte',
    label: METRIC_LABELS.productionHeadcount,
    category: 'Workforce',
    planKey: 'scheduledFte',
    actualKey: null,
    actualsKey: null,
    higherIsBetter: true,
    fmt: (v) => fmtNum(v, 1),
  },
  {
    key: 'productiveFte',
    label: METRIC_LABELS.productionFte,
    category: 'Workforce',
    planKey: 'productiveFte',
    actualKey: null,
    actualsKey: null,
    higherIsBetter: true,
    fmt: (v) => fmtNum(v, 1),
  },
  {
    key: 'hiring',
    label: METRIC_LABELS.hiringHeadcount,
    category: 'Workforce',
    planKey: 'hiringPlanned',
    actualKey: 'hiringActual',
    actualsKey: 'hiring',
    higherIsBetter: true,
    fmt: (v) => fmtNum(v, 0),
  },
  {
    key: 'attrition',
    label: METRIC_LABELS.attritionHeadcount,
    category: 'Workforce',
    planKey: 'attritionPlanned',
    actualKey: 'attritionActual',
    actualsKey: 'attrition',
    higherIsBetter: false,
    fmt: (v) => fmtNum(v, 1),
  },
  {
    key: 'scheduledHours',
    label: METRIC_LABELS.scheduledHours,
    category: 'Hours',
    planKey: 'scheduledHours',
    actualKey: null,
    actualsKey: 'scheduledHours',
    higherIsBetter: true,
    fmt: (v) => fmtNum(v, 0),
  },
  {
    key: 'payrollHours',
    label: METRIC_LABELS.payrollHours,
    category: 'Hours',
    planKey: 'payrollHours',
    actualKey: null,
    actualsKey: 'payrollHours',
    higherIsBetter: true,
    fmt: (v) => fmtNum(v, 0),
  },
  {
    key: 'productiveHours',
    label: METRIC_LABELS.productiveHours,
    category: 'Hours',
    planKey: 'productiveHours',
    actualKey: null,
    actualsKey: 'productiveHours',
    higherIsBetter: true,
    fmt: (v) => fmtNum(v, 0),
  },
  {
    key: 'otHours',
    label: METRIC_LABELS.otHours,
    category: 'Hours',
    planKey: 'otHours',
    actualKey: null,
    actualsKey: 'otHours',
    higherIsBetter: false,
    fmt: (v) => fmtNum(v, 0),
  },
  {
    key: 'vtoHours',
    label: METRIC_LABELS.vtoHours,
    category: 'Hours',
    planKey: 'vtoHours',
    actualKey: null,
    actualsKey: 'vtoHours',
    higherIsBetter: false,
    fmt: (v) => fmtNum(v, 0),
  },
  {
    key: 'shrinkageInOffice',
    label: METRIC_LABELS.shrinkageInOffice,
    category: 'Shrinkage',
    planKey: 'shrinkageInOfficeHours',
    actualKey: null,
    actualsKey: 'shrinkageInOfficeHours',
    higherIsBetter: false,
    fmt: (v) => fmtNum(v, 0),
  },
  {
    key: 'shrinkageOutOfOffice',
    label: METRIC_LABELS.shrinkageOutOfOffice,
    category: 'Shrinkage',
    planKey: 'shrinkageOutOfOfficeHours',
    actualKey: null,
    actualsKey: 'shrinkageOutOfOfficeHours',
    higherIsBetter: false,
    fmt: (v) => fmtNum(v, 0),
  },
  {
    key: 'occupancy',
    label: METRIC_LABELS.occupancy,
    category: 'Performance',
    planKey: 'occupancy',
    actualKey: null,
    actualsKey: 'occupancy',
    higherIsBetter: true,
    fmt: fmtPct,
    pct: true,
  },
  {
    key: 'productivity',
    label: METRIC_LABELS.productivity,
    category: 'Performance',
    planKey: 'productivity',
    actualKey: null,
    actualsKey: 'productivity',
    higherIsBetter: true,
    fmt: fmtPct,
    pct: true,
  },
  {
    key: 'utilization',
    label: METRIC_LABELS.utilization,
    category: 'Performance',
    planKey: 'utilization',
    actualKey: null,
    actualsKey: 'utilization',
    higherIsBetter: true,
    fmt: fmtPct,
    pct: true,
  },
  {
    key: 'serviceLevel',
    label: METRIC_LABELS.serviceLevel,
    category: 'Performance',
    planKey: 'serviceLevel',
    actualKey: null,
    actualsKey: 'serviceLevel',
    higherIsBetter: true,
    fmt: fmtPct,
    pct: true,
  },
  {
    key: 'forecastVolume',
    label: METRIC_LABELS.forecastVolume,
    category: 'Financial',
    planKey: 'forecastVolume',
    actualKey: null,
    actualsKey: 'forecastVolume',
    higherIsBetter: true,
    fmt: fmtNum,
  },
  {
    key: 'revenue',
    label: METRIC_LABELS.revenue,
    category: 'Financial',
    planKey: 'revenue',
    actualKey: null,
    actualsKey: 'revenue',
    higherIsBetter: true,
    fmt: fmtCurrency,
  },
  {
    key: 'totalCost',
    label: METRIC_LABELS.totalCost,
    category: 'Financial',
    planKey: 'totalCost',
    actualKey: null,
    actualsKey: 'cost',
    higherIsBetter: false,
    fmt: fmtCurrency,
  },
  {
    key: 'budgetVariance',
    label: METRIC_LABELS.budgetVariance,
    category: 'Financial',
    planKey: 'budgetVariance',
    actualKey: null,
    actualsKey: 'budget',
    higherIsBetter: true,
    fmt: fmtCurrency,
  },
  {
    key: 'laborCost',
    label: METRIC_LABELS.salaryCost,
    category: 'Financial',
    planKey: 'laborCost',
    actualKey: null,
    actualsKey: 'cost',
    higherIsBetter: false,
    fmt: fmtCurrency,
  },
  {
    key: 'trainingCost',
    label: METRIC_LABELS.trainingCost,
    category: 'Financial',
    planKey: 'trainingCost',
    actualKey: null,
    actualsKey: null,
    higherIsBetter: false,
    fmt: fmtCurrency,
  },
  {
    key: 'hiringCost',
    label: METRIC_LABELS.hiringCost,
    category: 'Financial',
    planKey: 'hiringCost',
    actualKey: null,
    actualsKey: null,
    higherIsBetter: false,
    fmt: fmtCurrency,
  },
  {
    key: 'totalCost',
    label: METRIC_LABELS.totalCost,
    category: 'Financial',
    planKey: 'totalCost',
    actualKey: null,
    actualsKey: 'cost',
    higherIsBetter: false,
    fmt: fmtCurrency,
  },
]
